apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nuit-info
  name: site
spec:
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              subPath: static-website
              name: static-website-volume
      volumes:
        - name: static-website-volume
          gitRepo:
            repository: https://github.com/EQUIPE-SUPER-SYMPA-Nuit-de-l-info/WEB